version: '2.4'

services:
  database:
    image: postgis/postgis
    container_name: flatinder-database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      # - ./.db/data:/var/lib/postgresql/data:z
      - ./.db/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080

  node:
    depends_on:
      - database
    build: docker/node
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
